version: '3.9'
services:
  my-api:
    image: compliment-generator-api
    build:
      context: .
      dockerfile: ./ComplimentGeneratorAPIv2/Dockerfile
    ports:
      - "32775:80"
      - "32776:443"
    enviroment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MinimumLogEventLevel=Warning
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"